Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 35

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Max: 25

Style/ClassVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15